### ISSUE TITLE
Header - Navigation:Text look smaller than design and adjust padding.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-Perth-Osteopathy#1]
![image](https://cloud.githubusercontent.com/assets/18587097/16719446/86f4892c-4754-11e6-8d0c-a7f696ebacca.png)

**Comment by Atcharanak** [comment]
Issue still happen.

![image](https://cloud.githubusercontent.com/assets/18587097/17163500/3acc44e8-53ea-11e6-826e-9d53b789f190.png)

**Comment by p-sangchan** [comment]
It's couldn't increase padding more than this, Cuz It'll fall to second rows over IE browser
