### ISSUE TITLE
Campaign monitor is not configured for Newsletter form.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-Perth-Osteopathy#116]
The first is how to set up
https://knowledgebase.titanweb.com.au/implementation/user-accounts/setup-campaign-monitor-account-for-client

The next how to connect to the client account
https://knowledgebase.titanweb.com.au/implementation/user-accounts/connect-newsletter-form-to-clients-campaign-monitor-account"

**Comment by p-sangchan** [comment]
Completed by Mailchimp and I've tested. PSB

![image](https://cloud.githubusercontent.com/assets/18692062/17426037/2bc019be-5afe-11e6-9a7d-96d1adf3305b.png)

**Comment by p-sangchan** [comment]
This site used 'Gravity Forms MailChimp Add-On' instead 'Forms Campaign Monitor Add-On'

PSA link for refer: https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/how-to-connect-gravity-forms-to-mailchimp
