### ISSUE TITLE
Product single: Unable to increase the quantity.  Drop down won’t work and unable to manually input.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-Perth-Osteopathy#122]
![image](https://cloud.githubusercontent.com/assets/18587097/17389984/e7ff38c0-5a32-11e6-9107-4098e79c8d11.png)

**Comment by p-sangchan** [comment]
As per discussed with PM this is already correct. 

we can improve the quantity of product by add them at the product back-end like below image.

and default value is 1 in case untick.

![image](https://cloud.githubusercontent.com/assets/18692062/17424501/9b61c5e8-5aee-11e6-8966-7e9341c566ac.png)

![image](https://cloud.githubusercontent.com/assets/18692062/17424515/cc237910-5aee-11e6-9e99-bf0bedc0e6ba.png)
