### ISSUE TITLE
Homepage - Banner: Form is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-Perth-Osteopathy#6]
![image](https://cloud.githubusercontent.com/assets/18587097/16720973/d9917bca-4765-11e6-92dd-f42aa95534fe.png)

**Comment by Atcharanak** [comment]
![image](https://cloud.githubusercontent.com/assets/18587097/17161672/97e5ef14-53d9-11e6-9483-9b1571ab777d.png)

**Comment by p-sangchan** [comment]
![image](https://cloud.githubusercontent.com/assets/18692062/17199992/b3fd8c2a-54ab-11e6-84f3-3dc52a5f2c45.png)
