### ISSUE TITLE
Homepage - W3C Error

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-Perth-Osteopathy#64]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwest-perth-osteopathy-imp.stage.titanweb.com.au%2F

![image](https://cloud.githubusercontent.com/assets/18587097/16788805/3061a570-48d2-11e6-8e56-570575083af1.png)

**Comment by p-sangchan** [comment]
Some issue couldn't fix it.

**Comment by Atcharanak** [comment]
What's issue could not fix?

![image](https://cloud.githubusercontent.com/assets/18587097/17166596/2623245e-5402-11e6-92f6-f099bf259d2a.png)
